### PR TITLE
Top-level expressions no longer drop line breaks.

### PR DESCRIPTION
**Pull request by PeterReid**
In topLevelExps, expressions spanning several lines would be condensed
down into a string with no line breaks. This is normally find, but not
when there is a string spanning several lines. Documentation strings
do that:

(defun foozle (x)
  ":Doc-Section foozle
  The one-liner ~/~/

  The extended documentation that will
  show up if you do :doc!"
  x)

Line breaks are part of docstrings' syntax, so this actually made some
valid function definitions no longer admit.

### CODE REVIEW

**Comment by calebegg** [comment]
There's also some stuff with the About window. Did you intend to include that in this pull request?

**Comment by PeterReid** [comment]
I didn't mean to include that.. I don't really know what I'm doing with github. I was going to do that one separately, since they aren't related.

**Comment by calebegg** [comment]
Ok. That's fine. I don't know what I'm doing either. I've only ever
submitted one pull request.

On Sat, Mar 31, 2012 at 16:34, Peter Reid <
reply@reply.github.com

**Comment by calebegg** [comment]
If you want, you can just make this one the AboutWindow change (if you're done with it).

**Comment by PeterReid** [comment]
(closing since the smaller pull request was merged)

**Pull request closed without merging**
